<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" class="navbar-toggle collapsed" type="button">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="/" class="navbar-brand">HOMER</a>
            <div class="brand-desc">
                Landing page for Homer app
            </div>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li class="active"><a class="page-scroll" href="/">Главная</a></li>
                <li><a class="page-scroll" page-scroll href="/register">Регистрация</a></li>
                <li><a class="page-scroll" page-scroll href="/login">Вход</a></li>
                <li><a class="page-scroll" page-scroll href="/profile">Мой профиль</a></li>
                <li><a class="page-scroll" page-scroll href="/logout">Выход</a></li>
            </ul>
        </div>
    </div>
</nav>
